FROM node:22

ENV NODE_ENV=production

WORKDIR /app

COPY services/scheduler/package*.json ./services/scheduler/
COPY packages/redis-client/package*.json ./packages/redis-client/

RUN cd services/scheduler && npm ci --omit=dev \
    && cd ../../packages/redis-client && npm ci --omit=dev

COPY services/scheduler ./services/scheduler
COPY services/worker ./services/worker
COPY packages ./packages

WORKDIR /app/services/scheduler

CMD ["node", "src/index.js"]
